-- Seed initial suggestion data
INSERT INTO "Suggestion" ("uuid", "category", "value", "updatedAt") VALUES
  (gen_random_uuid(), 'PAST_ACTION', 'threw coins off the top of the space needle trying to hit people. But soon upgraded to water balloons', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Got married of course! ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Locked pinkies and skipped off into the sunset, singing Somewhere Over the Rainbow', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Left to go look for their digits', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Went gravesite shopping at the cemetery for their vacation. ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Put on their big boy pants and stepped into moving traffic', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'solved world hunger, cured cancer, and explored the deepest parts of the ocean', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'went skydiving with the dog.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'read a book with a baby', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'ate all of the spaghettis', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'huffed and puffed and blew the house down', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'cried every time', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'attempted to put on each other''s straight jackets but you can''t put on someone else''s while you are wearing one.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Sold their birthrights for some stronger lungs.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Jumped on the trees and jumped on the houses and punched peoples cars ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'wrestled in a vat of warm milk and one of them died.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Physically entered the portal to the virtual world of the video game to save their cousin, but died from a squirtle.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Went camping in a haunted motorhome and the ghost Nate their spam', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Went alligator surfing during the hurricane in florida and saved all the flamingos', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'fell into the pit of quicksand as he screamed in terror, but she only sank down to her ankles so it ended up being fine. ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Retired from milking goats and started a business milking almonds ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Ran away', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PAST_ACTION', 'Frolicked throughout the corn maze until they arrived at the yellow brick road', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'dancing in the rain', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'eating spaghetti', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'driving to the airport', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'sledding down the hill', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'writing love letters', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'watching Shrek 2', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'washing potatoes', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'listening to white noise', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'snuggling with stuffed animals', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'reading a good book', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'coding up a fun game', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Dancing to that song Walk like a man like ya know in that song walk like a man. ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Bickering over who killed who', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Being towed in a wagon while in the Running of the Bulls', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Scuba diving in a pool of Jello ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Hiding from a murderer in a closet while talking loudly on a phone', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Playing mine sweeper looking to kill cute ducks', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Skipping down main street singing Christmas carols. ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Eating their curds and whey. Gross.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'walking on the beach and throwing the jellyfish back in the ocean', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Selling Seashells by the homeless man in an abandoned subway tunnel', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Looking lovingly into each others eyes. Gross.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'separating the good water from the bad water and punishing the bad water', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Particle colliding in their free time.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Watching a dcumentary about cannibalism', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Eating ice cream at a pizza place in new york', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'PRESENT_ACTION', 'Gossiping', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I like cheese', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'What did you call me?', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Why are you so mean?', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Did you mean to call or was it an accident?', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Look out!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'My reflexes are just fine, look!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Don''t throw that away, it could be useful!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Wait for me!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Okay, but no mayonnaise this time', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Can you grab the weekwhacker? I need to shave my back again', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Ok let''s go change. And this time I get the sparkly pink jumpsuit!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I haven''t thrown a great, big tantrum in a while...', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Will you marry me? ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Really? I thought I was the only one!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'We need to bring back milk men.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I am woman hear me roar', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I don''t read good', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Stop breathing.  It''s annoying!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Oh, what a beautiful mid-morning!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'It''s my birthday and I''ll cry if I want to, cry if I want to, cry cry cry CRY', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I can''t hear you over my inner demons ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'McDonals forgot my McNuggets….. we are about to have a McProblem', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Boost my bottom!!!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I don''t think we need to bring China into this', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I thought we were just changing a lightbulb, how did we end up here?', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'It''s hard to tap dance on the beach', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I love it when I stroll grandly through the ocean', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Make sure to save the wrapping paper and the bows', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I didn''t even think the new Star Wars movies were that bad', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Quick, let me feel!', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'New phone, who dis?', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Stop exhaling — you''re ruining the air and making the earth toxic', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'If you could be the one who if you were the greatest then if you were who you wanted to be for your parents?', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I hate to tell you this / but I have leprosy ', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'You woke me up for this?!?', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'What the frick?', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Well I never', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I don''t care who your mother is, I am going to get on that boat', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'That''s what she said', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Have you seen my spleen?', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Time to wake up to WOKE, fool.', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'Thinks for thanking of me', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'STATEMENT', 'I''m not as think as you drunk I am, ocifer', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Jason Bourne', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Jeff Bezos', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Elon Musk', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Mark Zuckerburg', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Justin Bieber', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Channing Tatum', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Robin Hood', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Shrek', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Jack Skellington', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Benjamin Franklin', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Joe Biden', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Chris Evans', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Alfred', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Rick Astley', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Grandpa', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Dad', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Mario', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Christian Bale', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Judas', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Humphrey Higgins', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Frankinstein', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Snape', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'MALE_NAME', 'Jafar', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Wynona Ryder', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'The Queen of England', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Fiona', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Mary', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Elsa', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Beyonce', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Grandma', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Mom', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Honey Boo Boo', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Princess Zelda', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Rashida Jones', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Leslie Knope', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Mariah Carey', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Queen Victoria', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Anastasia', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Dolores Umbridge', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Thumbelina', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Miss Piggy', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Hildegard von Bingen', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Ursula', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Melania Trump', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Xena warrior princess', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Leia', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'Michelle Obama', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'FEMALE_NAME', 'She-hulk', CURRENT_TIMESTAMP)
ON CONFLICT ("category", "value") DO NOTHING;
